[GLOBAL]
pants_version = "2.20.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.lint.ruff",
  "pants.backend.codegen.protobuf.python",  # optional
]

[python]
interpreter_constraints = [">=3.10"]
source_roots = ["src"]

[python-bootstrap]
