python_sources()

pex_binary(
    name="combine_events",
    entry_point="combine_events:main",
)

pex_binary(
    name="analyze_events",
    entry_point="analyze_events:main",
)

pex_binary(
    name="balance_tracker",
    entry_point="balance_tracker:main",
)
